# Copyright (c) 2025, Robotic Systems Lab - Legged Robotics at ETH Zürich
#
# SPDX-License-Identifier: BSD-3-Clause

from .terrain import (
    GAME_ARENA_BASE_CFG,
    GAME_ARENA_RANDOM_FLOORS_CFG,
    LESS_ROUGH_TERRAINS_CFG,
    MESH_FLAT_TERRAIN_CFG,
    MESH_PYRAMID_TERRAIN_CFG,
    MESH_STEPPABLE_PYRAMID_TERRAIN_CFG,
    OBSTACLE_TERRAIN_CFG,
    ONE_TERRAIN_CFG,
    ONLY_ROUGH_TERRAINS_CFG,
    PYRAMID_TERRAINS_CFG,
    SLIGHTLY_ROUGH_TERRAINS_CFG,
    TEST_ROUGH_TERRAINS_CFG,
    WALL_TERRAIN_CFG,
)
